services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - postgres

  postgres:
      image: postgres:16
      container_name: postgres_container
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: busstop
      ports:
        - "5432:5432"
      # volumes:
      #   - postgres_data:/var/lib/postgresql/data
      networks:
        - app_network

# volumes:
#   postgres_data:

networks:
  app_network:
    driver: host