version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark-master-data:/bitnami/spark
    networks:
      - spark-network
      
  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - spark-worker-data:/bitnami/spark
    networks:
      - spark-network

volumes:
  spark-master-data:
  spark-worker-data:

networks:
  spark-network:
    driver: bridge